---
title: "/usr/bin/time comparison isolated single threaded fastp and kma no pipe"
execute: 
  echo: false
  eval: true
format: html
editor: 
  markdown: 
    wrap: 80
---
```{r}
#load libraries
library(tidyverse)
library(ggpubr)
library(patchwork)
```

```{r}
raw_isolated_elapsed_data <- read_table("../../thesis_dir/data/new_data/isolated_times_fastp_kma.tsv")

raw_isolated_elapsed_data <- raw_isolated_elapsed_data |>
  select(fastp_1GB, fastp_5GB, kma_1GB, kma_5GB)
```


```{r}
isolated_elapsed_data_long <- raw_isolated_elapsed_data |>
  pivot_longer(cols = everything(), names_to = "name", values_to = "elapsed_time")

isolated_elapsed_data_long |> 
  ggbarplot(x = "name", y = "elapsed_time", color = "name", fill = "name", alpha = 0.1,
            palette = c("#00AFBB", "#E7B800", "#FC4E07", "#8A2BE2"),
            x.text.angle = 25,
            xlab = "non-pipe sample with file size",
            ylab = "Mean elapsed time (s)",
 add = c("mean_se"), label = TRUE, lab.size = 3) + rremove("legend") +
  theme(axis.text.x = element_text(size = 8))  + 
  plot_annotation(title = "Elapsed time of non-pipe fastp and kma for 1GB and 5GB paired end files",
                         subtitle = "Intel Xeon Gold 6226R (16 core, 2.90GHz)\ngcc/13.1.0")  &
    theme(plot.subtitle = element_text(size = 8))
```

